# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=False, unique=True),
        ),
    ]
