# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ManyToManyField(default=False, to='projects.Project', verbose_name='Name of Project '),
        ),
        migrations.AlterField(
            model_name='project',
            name='name_of_project',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
