# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160827_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ManyToManyField(to='projects.Project'),
        ),
    ]
