# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160827_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name_of_project',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
