# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160827_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name_of_document',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='pdf', validators=[projects.models.validation_file_extension]),
        ),
    ]
