# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160827_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='pdf', validators=[projects.models.validation_file_extension], verbose_name='Name of Document'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='projects.Project'),
        ),
    ]
