# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160828_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='modified',
        ),
    ]
