# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 18:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name of Candidate')),
                ('mobile', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile No.')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('work_exp', models.FloatField(verbose_name='Working Experience')),
                ('analytics_in_exp', models.BooleanField(default=False)),
                ('current_location', models.CharField(max_length=50, verbose_name='Current Location')),
                ('correct_location', models.CharField(max_length=50, verbose_name='Corrected Location')),
                ('near_city', models.CharField(max_length=50, verbose_name='Nearest City')),
                ('preferred_location', models.CharField(max_length=50, verbose_name='Preferred Location')),
                ('ctc', models.FloatField(verbose_name='CTC')),
                ('current_emp', models.CharField(blank=True, max_length=150, verbose_name='Current Employer')),
                ('current_deg', models.CharField(blank=True, max_length=150, verbose_name='Current Designation')),
                ('skills', models.CharField(max_length=200, verbose_name='Skills')),
                ('ug_course', models.CharField(max_length=30, verbose_name='U.G. Course')),
                ('ug_institution', models.CharField(max_length=150, verbose_name='U.G. Institution Name')),
                ('trier1', models.CharField(max_length=2, verbose_name='Trier 1')),
                ('ug_year_passing', models.CharField(max_length=4, verbose_name=' U.G. year of passing')),
            ],
        ),
    ]
