# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 19:46
from __future__ import unicode_literals

import career.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(upload_to='resume', validators=[career.models.validation_file_extension], verbose_name='Resume'),
        ),
    ]
