# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 20:04
from __future__ import unicode_literals

import career.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20160906_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ctc',
            field=models.FloatField(validators=[career.models.validation], verbose_name='CTC'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile No.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_exp',
            field=models.FloatField(validators=[career.models.validation], verbose_name='Working Experience'),
        ),
    ]
